// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 pcontacts contributors

package io.pcontacts.core.sync.contacts.encrypt

import io.pcontacts.core.crypto.openpgp.BouncyCastleOpenPgpService
import io.pcontacts.core.crypto.openpgp.VerificationStatus
import io.pcontacts.core.protoncontacts.CardEncryptRequest
import io.pcontacts.core.sync.contacts.decrypt.TestKeys
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

/**
 * Exercises [OpenPgpCardEncryptOp] with real BouncyCastle keys
 * generated by [TestKeys]. Validates that signed and encrypted cards
 * can be verified / decrypted with the same key ring — the encrypt→
 * decrypt round-trip the bidirectional sync depends on.
 */
class OpenPgpCardEncryptOpTest {

    private val openPgp = BouncyCastleOpenPgpService()
    private val passphrase = "test-passphrase".toCharArray()

    private lateinit var encryptOp: io.pcontacts.core.protoncontacts.CardEncryptOp

    @Before fun setUp() {
        val (_, unlocked) = TestKeys.armoredAndUnlocked(passphrase)
        encryptOp = OpenPgpCardEncryptOp.build(
            openPgp = openPgp,
            encryptionKeys = listOf(unlocked.public),
            signingKey = unlocked.private
        )
    }

    @Test fun sign_only_returns_plaintext_data_and_valid_signature() {
        val plaintext = "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Alice\r\nEND:VCARD"
        val outcome = encryptOp(CardEncryptRequest.SignOnly(plaintext))

        assertEquals(plaintext, outcome.data)
        assertTrue(outcome.signature.isNotBlank())
        assertTrue(outcome.signature.contains("BEGIN PGP SIGNATURE"))
    }

    @Test fun sign_only_signature_verifies_against_same_key() {
        val (_, unlocked) = TestKeys.armoredAndUnlocked("verify-pass".toCharArray())
        val op = OpenPgpCardEncryptOp.build(openPgp, listOf(unlocked.public), unlocked.private)
        val plaintext = "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Bob\r\nEND:VCARD"

        val outcome = op(CardEncryptRequest.SignOnly(plaintext))

        val status = openPgp.verifyDetached(
            plaintext = plaintext.toByteArray(Charsets.UTF_8),
            armoredSignature = outcome.signature,
            verificationKeys = listOf(unlocked.public)
        )
        assertEquals(VerificationStatus.SIGNED_AND_VALID, status)
    }

    @Test fun encrypt_and_sign_returns_armored_ciphertext_and_signature() {
        val plaintext = "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Alice\r\nEND:VCARD"
        val outcome = encryptOp(CardEncryptRequest.EncryptAndSign(plaintext))

        assertNotEquals(plaintext, outcome.data)
        assertTrue(outcome.data.contains("BEGIN PGP MESSAGE"))
        assertTrue(outcome.signature.contains("BEGIN PGP SIGNATURE"))
    }

    @Test fun encrypt_and_sign_round_trips_through_decrypt() {
        val (_, unlocked) = TestKeys.armoredAndUnlocked("roundtrip-pass".toCharArray())
        val op = OpenPgpCardEncryptOp.build(openPgp, listOf(unlocked.public), unlocked.private)
        val plaintext = "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Carol\r\nEND:VCARD"

        val outcome = op(CardEncryptRequest.EncryptAndSign(plaintext))

        val result = openPgp.decryptAndVerify(
            armoredMessage = outcome.data,
            detachedSignature = outcome.signature,
            decryptionKeys = unlocked.allPrivateKeys,
            verificationKeys = listOf(unlocked.public)
        )
        assertEquals(plaintext, String(result.plaintext, Charsets.UTF_8))
        assertEquals(VerificationStatus.SIGNED_AND_VALID, result.verificationStatus)
    }
}
