// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 pcontacts contributors

package io.pcontacts.core.storage

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * ADR-0009 second crypto layer for the mailbox keyPassword: a Keystore-
 * backed AES-256-GCM key under the alias `pcontacts.kekv1`. Wrapping
 * the keyPassword under a Keystore key (rather than relying on
 * EncryptedSharedPreferences alone) gives us:
 *   - Hardware-backed key isolation on StrongBox / TEE devices.
 *   - A clean rotation point (rotate the alias on full re-auth).
 *   - A future hook for user-presence binding (biometric) without
 *     touching the keyPassword bytes themselves.
 *
 * Wire format for `wrap()` output:
 *   [0..11]  random 96-bit IV
 *   [12..]   GCM ciphertext + 128-bit tag
 *
 * The IV travels in the clear; the GCM tag is appended to the ciphertext
 * by the Cipher API.
 */
class KeystoreAesGcmKek(
    private val alias: String = DEFAULT_ALIAS
) {

    fun wrap(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val iv = cipher.iv                       // 12 bytes for GCM, generated by the provider
        require(iv.size == IV_BYTES) { "expected 12-byte GCM IV, got ${iv.size}" }
        val ciphertext = cipher.doFinal(plaintext)
        return iv + ciphertext
    }

    fun unwrap(wrapped: ByteArray): ByteArray {
        require(wrapped.size > IV_BYTES) { "wrapped payload too short" }
        val iv = wrapped.copyOfRange(0, IV_BYTES)
        val ciphertext = wrapped.copyOfRange(IV_BYTES, wrapped.size)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
        return cipher.doFinal(ciphertext)
    }

    /** Deletes the alias entirely. Subsequent `wrap()` will provision a fresh key. */
    fun delete() {
        val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        if (ks.containsAlias(alias)) ks.deleteEntry(alias)
    }

    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        val existing = ks.getKey(alias, null) as? SecretKey
        if (existing != null) return existing

        val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
        gen.init(
            KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // User-presence binding (biometric) is intentionally NOT enabled
                // here so background sync can decrypt without a foreground UI.
                // The opt-in biometric variant lands in a later commit.
                .build()
        )
        return gen.generateKey()
    }

    companion object {
        const val DEFAULT_ALIAS: String = "pcontacts.kekv1"
        private const val KEYSTORE_PROVIDER: String = "AndroidKeyStore"
        private const val IV_BYTES: Int = 12
        private const val GCM_TAG_BITS: Int = 128
    }
}
