// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 pcontacts contributors

package io.pcontacts.core.storage

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import androidx.annotation.RequiresApi
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * ADR-0009: the AES-256-GCM key under the alias `pcontacts.kekv1` in
 * the Android Keystore, the only cipher for every `SecretStore` value
 * and for the persisted merge base (ADR-0018). StrongBox is requested
 * on API 28+ and the TEE is the fallback when the device has none.
 *
 * The key is created by the first [wrap] after sign-in and deleted —
 * verifiably — at logout. [unwrap] never creates a key: once the alias
 * is gone, everything sealed under it reads as absent, which is the
 * point of deleting it.
 *
 * Wire format for `wrap()` output:
 *   [0..11]  random 96-bit IV
 *   [12..]   GCM ciphertext + 128-bit tag
 *
 * The IV travels in the clear; the GCM tag is appended to the ciphertext
 * by the Cipher API. User-presence binding (biometric) is intentionally
 * NOT enabled so background sync can decrypt without a foreground UI.
 */
class KeystoreAesGcmKek(
    private val alias: String = DEFAULT_ALIAS
) : SecretCipher {

    override fun wrap(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getKey() ?: createKey())
        val iv = cipher.iv                       // 12 bytes for GCM, generated by the provider
        require(iv.size == IV_BYTES) { "expected 12-byte GCM IV, got ${iv.size}" }
        val ciphertext = cipher.doFinal(plaintext)
        return iv + ciphertext
    }

    override fun unwrap(wrapped: ByteArray): ByteArray {
        require(wrapped.size > IV_BYTES) { "wrapped payload too short" }
        val key = getKey() ?: throw KekMissingException(alias)
        val iv = wrapped.copyOfRange(0, IV_BYTES)
        val ciphertext = wrapped.copyOfRange(IV_BYTES, wrapped.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, iv))
        return cipher.doFinal(ciphertext)
    }

    override fun delete() {
        val ks = keyStore()
        if (ks.containsAlias(alias)) ks.deleteEntry(alias)
        check(!ks.containsAlias(alias)) { "Keystore alias survived deleteEntry" }
    }

    private fun keyStore(): KeyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }

    private fun getKey(): SecretKey? = keyStore().getKey(alias, null) as? SecretKey

    private fun createKey(): SecretKey {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            createStrongBoxKey()?.let { return it }
        }
        return generate(strongBox = false)
    }

    /** Null when the device has no StrongBox; the caller then generates a TEE key. */
    @RequiresApi(Build.VERSION_CODES.P)
    private fun createStrongBoxKey(): SecretKey? =
        try {
            generate(strongBox = true)
        } catch (_: StrongBoxUnavailableException) {
            null
        }

    private fun generate(strongBox: Boolean): SecretKey {
        val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
        val spec = KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_BITS)
        if (strongBox && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) spec.setIsStrongBoxBacked(true)
        gen.init(spec.build())
        return gen.generateKey()
    }

    companion object {
        const val DEFAULT_ALIAS: String = "pcontacts.kekv1"
        private const val KEYSTORE_PROVIDER: String = "AndroidKeyStore"
        private const val TRANSFORMATION: String = "AES/GCM/NoPadding"
        private const val IV_BYTES: Int = 12
        private const val GCM_TAG_BITS: Int = 128
        private const val KEY_BITS: Int = 256
    }
}
