// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 pcontacts contributors

package io.pcontacts.core.crypto

import io.pcontacts.core.crypto.bcrypt.ComputeKeyPassword
import io.pcontacts.core.crypto.bcrypt.SrpHashPassword
import io.pcontacts.core.crypto.openpgp.BouncyCastleKeyUnlock
import io.pcontacts.core.crypto.openpgp.BouncyCastleOpenPgpService
import io.pcontacts.core.crypto.openpgp.VerificationStatus
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeNotNull
import org.junit.Test

/**
 * Plan §17 task 9 — pins the Kotlin port against vectors captured
 * from `@protontech/crypto`. The JSON lives at
 * `core/crypto/src/test/resources/proton-crypto-vectors.json` and
 * is generated by `tools/vectors/capture.js`.
 *
 * Parsing is intentionally hand-rolled (no kotlinx-serialization
 * dependency in :core:crypto test scope) so the test file is
 * self-contained.
 */
class CapturedVectorsTest {

    @Test fun computeKeyPassword_matches_captured_vectors() {
        val vectors = loadVectors() ?: return
        val keyPasswordArray = vectors.regexFind("\"computeKeyPassword\"\\s*:\\s*\\[(.*?)\\]")
            ?: return
        val entryRegex = Regex(
            "\"label\"\\s*:\\s*\"([^\"]+)\".*?" +
                "\"password\"\\s*:\\s*\"((?:\\\\.|[^\"])*)\".*?" +
                "\"saltB64\"\\s*:\\s*\"([^\"]+)\".*?" +
                "\"expected\"\\s*:\\s*\"([^\"]+)\"",
            RegexOption.DOT_MATCHES_ALL
        )
        var checked = 0
        for (match in entryRegex.findAll(keyPasswordArray)) {
            val (label, passwordEscaped, saltB64, expected) = match.destructured
            val password = unescapeJson(passwordEscaped)
            val actual = ComputeKeyPassword.derive(password.toCharArray(), saltB64)
            assertEquals("computeKeyPassword vector '$label' mismatch", expected, actual)
            checked += 1
        }
        if (checked == 0) return
    }

    @Test fun srpHashPassword_matches_captured_vectors() {
        val vectors = loadVectors() ?: return
        // srpHashPassword is a top-level array whose entries may contain long
        // modulusHex fields — use a greedy-per-entry regex with lazy inner matches.
        val srpArray = vectors.regexFind("\"srpHashPassword\"\\s*:\\s*\\[(.*?)\\](?=\\s*,\\s*\"openPgp\")")
            ?: return
        val entryRegex = Regex(
            "\\{[^}]*?" +
                "\"label\"\\s*:\\s*\"([^\"]+)\".*?" +
                "\"password\"\\s*:\\s*\"((?:\\\\.|[^\"])*)\".*?" +
                "\"saltB64\"\\s*:\\s*\"([^\"]+)\".*?" +
                "\"modulusHex\"\\s*:\\s*\"([^\"]+)\".*?" +
                "\"expectedHex\"\\s*:\\s*\"([^\"]+)\"" +
                "[^}]*\\}",
            RegexOption.DOT_MATCHES_ALL
        )
        var checked = 0
        for (match in entryRegex.findAll(srpArray)) {
            val (label, passwordEscaped, saltB64, modulusHex, expectedHex) = match.destructured
            val password = unescapeJson(passwordEscaped)
            val modulusBytes = hexToBytes(modulusHex)
            val actual = SrpHashPassword.derive(password.toCharArray(), saltB64, modulusBytes)
            assertEquals(
                "srpHashPassword vector '$label' mismatch",
                expectedHex,
                actual.toHex()
            )
            checked += 1
        }
        if (checked == 0) return
    }

    @Test fun openPgp_matches_captured_vectors() {
        val vectors = loadVectors() ?: return
        val entries = extractOpenPgpEntries(vectors)
        if (entries.isEmpty()) return

        val service = BouncyCastleOpenPgpService()
        var checked = 0

        for (entry in entries) {
            val label = entry.jsonString("label")!!
            val operation = entry.jsonString("operation")!!
            val plaintext = unescapeJson(entry.jsonStringRaw("plaintext")!!)
            val armoredPrivateKey = unescapeJson(entry.jsonStringRaw("armoredPrivateKey")!!)

            // Import the OpenPGP.js-generated key via BouncyCastle.
            // The public key is extracted from the secret key ring — we don't
            // need to parse armoredPublicKey separately.
            val unlocked = BouncyCastleKeyUnlock.unlock(armoredPrivateKey, CharArray(0))

            when (operation) {
                "signDetached" -> {
                    val armoredSignature = unescapeJson(entry.jsonStringRaw("armoredSignature")!!)

                    // Verify the JS-produced signature with the BouncyCastle verifier.
                    // OpenPGP.js binary-mode signatures use BINARY_DOCUMENT type.
                    val status = service.verifyDetached(
                        plaintext = plaintext.toByteArray(Charsets.UTF_8),
                        armoredSignature = armoredSignature,
                        verificationKeys = listOf(unlocked.public),
                        canonicalText = false,
                        stripTrailingSpaces = false
                    )
                    assertEquals(
                        "openPgp vector '$label': JS signature should verify in BC",
                        VerificationStatus.SIGNED_AND_VALID,
                        status
                    )

                    // Also sign with BouncyCastle and verify our own signature —
                    // proves the round-trip path works with the imported key.
                    val bcSig = service.signDetached(
                        plaintext = plaintext.toByteArray(Charsets.UTF_8),
                        signingKey = unlocked.private,
                        canonicalText = false,
                        stripTrailingSpaces = false
                    )
                    assertTrue(
                        "openPgp vector '$label': BC signature should be armored",
                        bcSig.contains("-----BEGIN PGP SIGNATURE-----")
                    )
                    val bcStatus = service.verifyDetached(
                        plaintext = plaintext.toByteArray(Charsets.UTF_8),
                        armoredSignature = bcSig,
                        verificationKeys = listOf(unlocked.public),
                        canonicalText = false,
                        stripTrailingSpaces = false
                    )
                    assertEquals(
                        "openPgp vector '$label': BC-produced signature should verify",
                        VerificationStatus.SIGNED_AND_VALID,
                        bcStatus
                    )
                }
                "encryptAndSignDetached" -> {
                    val armoredMessage = unescapeJson(entry.jsonStringRaw("armoredMessage")!!)
                    val armoredDetachedSig = unescapeJson(entry.jsonStringRaw("armoredDetachedSignature")!!)

                    // Decrypt the JS-encrypted message with BouncyCastle.
                    val decrypted = service.decryptAndVerify(
                        armoredMessage = armoredMessage,
                        detachedSignature = null,
                        decryptionKeys = unlocked.allPrivateKeys,
                        verificationKeys = listOf(unlocked.public)
                    )
                    assertArrayEquals(
                        "openPgp vector '$label': decrypted plaintext should match",
                        plaintext.toByteArray(Charsets.UTF_8),
                        decrypted.plaintext
                    )

                    // Verify the JS-produced detached signature separately.
                    val sigStatus = service.verifyDetached(
                        plaintext = plaintext.toByteArray(Charsets.UTF_8),
                        armoredSignature = armoredDetachedSig,
                        verificationKeys = listOf(unlocked.public),
                        canonicalText = false,
                        stripTrailingSpaces = false
                    )
                    assertEquals(
                        "openPgp vector '$label': JS detached signature should verify in BC",
                        VerificationStatus.SIGNED_AND_VALID,
                        sigStatus
                    )
                }
                else -> error("unknown openPgp operation: $operation")
            }
            checked += 1
        }
        assertTrue("expected at least 1 openPgp vector", checked > 0)
    }

    // ------------------------------------------------------------------
    // OpenPGP vector JSON extraction helpers
    // ------------------------------------------------------------------

    /**
     * Extracts individual JSON object strings from the `openPgp` array.
     * Since armored PGP strings never contain unescaped `{` or `}`,
     * we can safely split on top-level braces.
     */
    private fun extractOpenPgpEntries(json: String): List<String> {
        // Find the start of the openPgp array
        val arrayStart = Regex("\"openPgp\"\\s*:\\s*\\[").find(json) ?: return emptyList()
        val startIdx = arrayStart.range.last + 1
        // Find each top-level { ... } object within the array
        val entries = mutableListOf<String>()
        var i = startIdx
        while (i < json.length) {
            when (json[i]) {
                '{' -> {
                    val objStart = i
                    var depth = 1
                    var inString = false
                    var escaped = false
                    i++
                    while (i < json.length && depth > 0) {
                        val c = json[i]
                        if (escaped) { escaped = false; i++; continue }
                        if (c == '\\' && inString) { escaped = true; i++; continue }
                        if (c == '"') inString = !inString
                        if (!inString) {
                            if (c == '{') depth++
                            else if (c == '}') depth--
                        }
                        i++
                    }
                    entries += json.substring(objStart, i)
                }
                ']' -> break
                else -> i++
            }
        }
        return entries
    }

    /**
     * Extracts a JSON string value by field name, returning the raw
     * (still JSON-escaped) content. Uses a manual scanner instead of
     * regex to avoid stack overflow on long armored PGP strings.
     */
    private fun String.jsonStringRaw(fieldName: String): String? {
        val needle = "\"$fieldName\""
        var pos = indexOf(needle)
        while (pos >= 0) {
            var i = pos + needle.length
            // skip whitespace and colon
            while (i < length && this[i].let { it == ' ' || it == '\t' || it == '\n' || it == '\r' }) i++
            if (i >= length || this[i] != ':') { pos = indexOf(needle, pos + 1); continue }
            i++
            while (i < length && this[i].let { it == ' ' || it == '\t' || it == '\n' || it == '\r' }) i++
            if (i >= length || this[i] != '"') { pos = indexOf(needle, pos + 1); continue }
            // Now at the opening quote — scan for the unescaped closing quote
            i++ // skip opening "
            val start = i
            while (i < length) {
                val c = this[i]
                if (c == '\\') { i += 2; continue }
                if (c == '"') return substring(start, i)
                i++
            }
            return null
        }
        return null
    }

    /** Shorthand: extract + unescape in one call (for simple fields). */
    private fun String.jsonString(fieldName: String): String? =
        jsonStringRaw(fieldName)?.let { unescapeJson(it) }

    private fun loadVectors(): String? {
        val stream = javaClass.getResourceAsStream("/proton-crypto-vectors.json")
        assumeNotNull(stream)
        return stream?.use { it.readBytes().toString(Charsets.UTF_8) }
    }

    private fun String.regexFind(pattern: String): String? =
        Regex(pattern, RegexOption.DOT_MATCHES_ALL).find(this)?.groupValues?.getOrNull(1)

    private fun unescapeJson(s: String): String {
        val sb = StringBuilder(s.length)
        var i = 0
        while (i < s.length) {
            val c = s[i]
            if (c == '\\' && i + 1 < s.length) {
                when (val n = s[i + 1]) {
                    '"', '\\', '/' -> sb.append(n)
                    'n' -> sb.append('\n')
                    'r' -> sb.append('\r')
                    't' -> sb.append('\t')
                    'b' -> sb.append('\b')
                    'u' -> {
                        if (i + 5 < s.length) {
                            sb.append(s.substring(i + 2, i + 6).toInt(16).toChar())
                            i += 4
                        }
                    }
                    else -> sb.append(n)
                }
                i += 2
            } else {
                sb.append(c)
                i += 1
            }
        }
        return sb.toString()
    }

    @Suppress("SameParameterValue")
    private fun hexToBytes(hex: String): ByteArray {
        val len = hex.length / 2
        val out = ByteArray(len)
        for (i in 0 until len) {
            out[i] = hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
        return out
    }

    private fun ByteArray.toHex(): String =
        joinToString("") { "%02x".format(it) }
}
