// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 pcontacts contributors

package io.pcontacts.core.crypto

import io.pcontacts.core.crypto.bcrypt.ComputeKeyPassword
import org.junit.Assert.assertEquals
import org.junit.Assume.assumeNotNull
import org.junit.Test

/**
 * Plan §17 task 9 — pins the Kotlin port against vectors captured
 * from `@protontech/crypto`. The JSON lives at
 * `core/crypto/src/test/resources/proton-crypto-vectors.json` and
 * is generated by `tools/vectors/capture.js`.
 *
 * Parsing is intentionally hand-rolled (no kotlinx-serialization
 * dependency in :core:crypto test scope) so the test file is
 * self-contained.
 */
class CapturedVectorsTest {

    @Test fun computeKeyPassword_matches_captured_vectors() {
        val vectors = loadVectors() ?: return
        val keyPasswordArray = vectors.regexFind("\"computeKeyPassword\"\\s*:\\s*\\[(.*?)\\]")
            ?: return
        val entryRegex = Regex(
            "\"label\"\\s*:\\s*\"([^\"]+)\".*?" +
                "\"password\"\\s*:\\s*\"((?:\\\\.|[^\"])*)\".*?" +
                "\"saltB64\"\\s*:\\s*\"([^\"]+)\".*?" +
                "\"expected\"\\s*:\\s*\"([^\"]+)\"",
            RegexOption.DOT_MATCHES_ALL
        )
        var checked = 0
        for (match in entryRegex.findAll(keyPasswordArray)) {
            val (label, passwordEscaped, saltB64, expected) = match.destructured
            val password = unescapeJson(passwordEscaped)
            val actual = ComputeKeyPassword.derive(password.toCharArray(), saltB64)
            assertEquals("computeKeyPassword vector '$label' mismatch", expected, actual)
            checked += 1
        }
        if (checked == 0) return
    }

    private fun loadVectors(): String? {
        val stream = javaClass.getResourceAsStream("/proton-crypto-vectors.json")
        assumeNotNull(stream)
        return stream?.use { it.readBytes().toString(Charsets.UTF_8) }
    }

    private fun String.regexFind(pattern: String): String? =
        Regex(pattern, RegexOption.DOT_MATCHES_ALL).find(this)?.groupValues?.getOrNull(1)

    private fun unescapeJson(s: String): String {
        val sb = StringBuilder(s.length)
        var i = 0
        while (i < s.length) {
            val c = s[i]
            if (c == '\\' && i + 1 < s.length) {
                when (val n = s[i + 1]) {
                    '"', '\\', '/' -> sb.append(n)
                    'n' -> sb.append('\n')
                    'r' -> sb.append('\r')
                    't' -> sb.append('\t')
                    'b' -> sb.append('\b')
                    'u' -> {
                        if (i + 5 < s.length) {
                            sb.append(s.substring(i + 2, i + 6).toInt(16).toChar())
                            i += 4
                        }
                    }
                    else -> sb.append(n)
                }
                i += 2
            } else {
                sb.append(c)
                i += 1
            }
        }
        return sb.toString()
    }
}
