# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2026 pcontacts contributors

# GitHub Dependabot — automated dependency update PRs.
# ADR-0015: every PR this generates still goes through
# checkForbiddenDependencies + checkLicense in CI.

version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "deps"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
