// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 pcontacts contributors
//
// Captures @protontech/crypto test vectors that the Kotlin port in
// :core:crypto verifies itself against. Plan §17 task 9.
//
// Outputs a single JSON file (default:
// ../../core/crypto/src/test/resources/proton-crypto-vectors.json)
// that the Kotlin-side CapturedVectorsTest consumes via the
// classpath.
//
// Run once when @protontech/crypto changes:
//   cd tools/vectors && npm install && node capture.js
//
// The script is intentionally NOT shipped in the APK — it lives in
// tools/ alongside Gradle scripts and CI helpers.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// =============================================================================
// Adapter layer — the @protontech/crypto package name + exports have shifted
// across versions; collect the lookups here so the rest of the script doesn't
// care.
// =============================================================================

let cryptoApi;
try {
  // Real package — npm install pulls it in.
  cryptoApi = require('@protontech/crypto');
} catch (e) {
  console.error(
    'FAIL: @protontech/crypto is not installed.\n' +
    '      Run `npm install` in tools/vectors before invoking the script.\n' +
    '      Error: ' + e.message
  );
  process.exit(1);
}

// The named exports we need. Some are async; the wrapper layer normalises.
//   - bcryptSHA512(password, salt) -> Promise<string>  (full bcrypt $2y$10$… string)
//   - SrpClient                                        (constructor with .computeProof)
//   - or low-level: hashPassword + generateClientProof
//
// If the lookup fails the script reports which export is missing so the user
// can pin a different version.
const required = [
  'bcryptSHA512',
];
for (const sym of required) {
  if (typeof cryptoApi[sym] !== 'function') {
    console.error(`FAIL: @protontech/crypto does not export "${sym}". Aborting.`);
    process.exit(1);
  }
}

// =============================================================================
// Vector inputs — picked to exercise each code path of the Kotlin port:
//   - bcrypt: short / long / unicode passwords + the documented 16-byte salt
//   - SRP: 2048-bit modulus + deterministic client ephemeral
//   - OpenPGP: round-trip encrypt+sign with a known keypair
// =============================================================================

const BCRYPT_INPUTS = [
  { label: 'ascii-short',  password: 'pass',        saltHex: '00010203040506070809101112131415' },
  { label: 'ascii-long',   password: 'correct horse battery staple', saltHex: 'aabbccddeeff00112233445566778899' },
  { label: 'utf8-unicode', password: 'pässwörd-Ω',  saltHex: 'deadbeefcafefacef00dbabe12345678' },
];

// =============================================================================
// Capture loops
// =============================================================================

async function captureBcrypt() {
  const out = [];
  for (const inp of BCRYPT_INPUTS) {
    const saltBytes = Buffer.from(inp.saltHex, 'hex');
    if (saltBytes.length !== 16) {
      throw new Error(`bcrypt salt must be 16 bytes; got ${saltBytes.length} for ${inp.label}`);
    }
    const saltB64 = saltBytes.toString('base64');
    const expected = await cryptoApi.bcryptSHA512(inp.password, saltBytes);
    out.push({
      label: inp.label,
      password: inp.password,
      saltB64,
      expected
    });
  }
  return out;
}

async function captureSrp() {
  // SRP capture deferred until the @protontech/crypto SRP surface lands in
  // this version. The Kotlin port's SrpClientTest already verifies against
  // RFC 5054 vectors; replacing those with Proton-derived ones flips its
  // [A] marker to [V]. If your installed version exposes a deterministic
  // SRP helper, extend this function and add SRP_INPUTS above.
  return [];
}

async function captureOpenPgp() {
  // OpenPGP capture deferred for the same reason — pick the right export
  // (decryptMessage / encryptMessage / signMessage) and document which
  // signature subtype Proton uses (BINARY vs CANONICAL_TEXT) for each
  // card type.
  return [];
}

// =============================================================================
// Main
// =============================================================================

(async () => {
  try {
    const bcryptVectors = await captureBcrypt();
    const srpVectors = await captureSrp();
    const openPgpVectors = await captureOpenPgp();

    const out = {
      generatedAt: new Date().toISOString(),
      protonCryptoPackageVersion: tryReadVersion(),
      schemaVersion: 1,
      notes: [
        'Generated by tools/vectors/capture.js — do not edit by hand.',
        'Add new inputs there + re-run; commit the resulting JSON alongside the script change.'
      ],
      bcryptSha512: bcryptVectors,
      srp: srpVectors,
      openPgp: openPgpVectors
    };

    const targetDir = path.resolve(__dirname, '..', '..', 'core', 'crypto', 'src', 'test', 'resources');
    if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });
    const targetPath = path.join(targetDir, 'proton-crypto-vectors.json');
    fs.writeFileSync(targetPath, JSON.stringify(out, null, 2) + '\n', 'utf8');

    console.log(`Wrote ${out.bcryptSha512.length} bcrypt, ${out.srp.length} SRP, ${out.openPgp.length} OpenPGP vectors`);
    console.log(`     → ${targetPath}`);
  } catch (e) {
    console.error('capture failed:', e && e.stack ? e.stack : e);
    process.exit(2);
  }
})();

function tryReadVersion() {
  try {
    const pkg = require('@protontech/crypto/package.json');
    return pkg.version || 'unknown';
  } catch {
    return 'unknown';
  }
}
